### ISSUE TITLE
create tag/release

### ISSUE THREAD

**Issue by rwaffen** [python-oca/python-oca#2]
Hiho everyone...

"it would be nice to have tags or "releases". so you can use this in your python setup and not to reference the master"

is it okay for the other, if i create a tag "1.0.0"?

**Comment by mattthias** [comment]
We only forgot to push the tags from the old repository. I did this now so we have the old tags preserved. Until we update the documentation and settle with tests and stuf we should not tag a new release.

**Comment by rwaffen** [comment]
ah cool, thanks... 
for all the new stuff we should also plan a tag or something. so that others can rely on this tag and we can move forwards on the master... or how is the opinion of the team for that?

**Comment by michael-os** [comment]
I wouldn't currently tag a release, since the library is somewhat lingering in a twilight world between OpenNebula 3.0 and 4.10 compatibility. I will go through the remaining compatibility issues in the next couple of days and make sure that the whole library is compatible with OpenNebula 4.10. If someone else volunteers to add some more useful documentation, we could then create a useful tag.

**Comment by mattthias** [comment]
Ho ho ho @rwaffen ,

please see  https://github.com/python-oca/python-oca/tree/4.10.0 for the latest tag 4.10.0 and https://pypi.python.org/pypi/oca for the updated package on pypi.

Best wishes and merry christmas,
Matthias

**Comment by rwaffen** [comment]
oh thanks… :smile:

**Comment by netcoding** [comment]
very merry christmas
